name: init
on:
  create:
    branches:
      - master
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: bash .github/workflows/scripts/init.sh
    - name: Commit files
      run: |
        git config --global user.name 'Alexis Lemaire'
        git config --global user.email 'a.lemaire@klimapartner.de'
        git rm .github/workflows/init.yml
        git rm .github/workflows/scripts/init.sh
        git commit -am "Initial commit"
        git push
