name: init
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init
      if: ${{ github.event.base_ref }} == null
      run: bash .github/workflows/scripts/init.sh
