name: init
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Init
      if: github.event.base_ref == 'null'
      run: bash .github/workflows/scripts/init.sh
