name: init
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init
      if: github.repository != 'kaskadi/template-action'
      run: bash .github/workflows/scripts/init.sh
