name: init
on:
  create:
    branches:
      - master
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: bash .github/workflows/scripts/init.sh
